### ISSUE TITLE
Invalid composer.json

### ISSUE THREAD

**Issue by derJake** [carsten-walther/html2pdf#1]
**Expected behaviour:**
Adding repo URL and walther/html2pdf to project's composer.json will install the extension.

**Observed behaviour:**
Composer returns 

> No valid composer.json was found in any branch or tag of https://github.com/carsten-walther/html2pdf.git, could not load a package from it. 

**Possible Solution:**
Running composer validate shows the version constraint being in the wrong format:
>  [UnexpectedValueException]                                                                
  Could not parse version constraint 9.5.0-10.4.99: Invalid version string "9.5.0-10.4.99"

Adding spaces around the hyphen leads to composer correctly validating the composer.json

**Comment by carsten-walther** [comment]
fixed in master branch
