### ISSUE TITLE
error wkhtmltopdf:127 

### ISSUE THREAD

**Issue by EnzephaloN** [carsten-walther/html2pdf#2]
Installed html2pdf inside 9.5.19 and tried to use with my extension. Former I used webkitpdf.
Tried the URL https://www.domain.com/?id=11&tx_some_extbase_params&type=8080 .
Returned error 127.
I went to Settings and gave html2pdf the full path of my wkhtmltopdf-binary and switched to "custom".
Error still exists.
If I use the full path from Settings in console, it works - no errors.

Any hints for me?
Best regards.

**Comment by EnzephaloN** [comment]
Oh sorry, error went away and was replaced by another error which points to Converter.php line 107 and a Developer log.

**Comment by EnzephaloN** [comment]
After fiddling around, because I need to print a pdf of a different page-type, I got a configuration which seems to work. Instead of trying to print a differerent page-type now the html2pdf-page-type gets the content & config to print. It throws no errors, so I think, something works.

But sadly, I get no pdf-file. My browser says "error loading PDF-document". 
I used wget, to load the page with typeNum=8080 and get a html-file instead a rendered pdf-file.

Checked Typo3 protocols:  no errors at html2pdf

**Comment by carsten-walther** [comment]
- Did you use the correct version for your operation system?
- Is the binary of wkhtmltopdf executeable?
- Did you set the correct path to your wkhtmltopdf version?
- Did you use the deafult typoscript settings of the extension?

The properties no_cache and no_search in the page you like to print as pdf has to be off (false).

**Comment by EnzephaloN** [comment]
Hello
Thanks for your answer.
wkhtmltopdf is 0.12.3, runs as expected, is executable and path is correct (like the TYPO3-protocoll said too).
with default-typoscript I get a `[ERROR] request="ece94db206ceb" component="Walther.Html2pdf.Converter.Converter": wkhtmltopdf threw an error when trying to create a PDF. Developers see the developer log for more information.` With my typoscript (getting rid of some binOptions like head and foot and applying the special page-type and content) I get the HTML instead of PDF.
I set `page.config.no_cache = 0` and `page.config.no_search = 0` by TS to type8080.
And no, there are no errors in error_log.

**Comment by carsten-walther** [comment]
Are there any errors in the TYPO3 error log?

**Comment by EnzephaloN** [comment]
getting forward...
now, after fixing a typo, I get a PDF. But sadly without my content, just the page-title.

**Comment by EnzephaloN** [comment]
````html2pdf.config.tx_html2pdf > 
html2pdf.config.tx_html2pdf{
  enable = 1
  enable.if.isFalse.data = TSFE:no_cache
  download_instead_preview = 1
  binOptions{
    encoding = utf-8
    orientation = Portrait
    page-size = A4
    page-width = 210
    page-height = 297
    page-offset = 0
    viewport-size = 1280x1024
    zoom = 1.0
    dpi = 300
    image-dpi = 300
    image-quality = 75
    enable-javascript = 
    no-outline = 
    disable-smart-shrinking =
  }
}
html2pdf.config.additionalHeaders.20.header = Content-Disposition: inline; filename=_accreditation.pdf
html2pdfconfig < html2pdf.config
html2pdf >
html2pdf = PAGE
html2pdf{
  10 = FLUIDTEMPLATE
  10.file = EXT:accreditation/Resources/Private/Layouts/Accreditationpdffluidtemplate.html
  typeNum = 8080
  includeCSS.file5 = EXT:accreditation/Resources/Public/Css/AccreditationFrontend.css
  includeCSS.media = screen,print
  config < html2pdfconfig
}
[request.getQueryParams()['type'] == '8080']
  page.config.no_cache = 0
  page.config.no_search = 0
  lib.pdfausgabe = COA
  lib.pdfausgabe.10 < styles.content.get
  lib.partner.wrap = |
[end]
html2pdfRenderer < html2pdf
html2pdfRenderer{
  typeNum = 8081
  config >
}````

**Comment by carsten-walther** [comment]
Okay, this seems not to be a bug of this extension. So the issue will be closed.
