### ISSUE TITLE
Broken Backend Module -> Reports, because of deprecated use of "contentPostProc-output" hook.

### ISSUE THREAD

**Issue by eckonator** [carsten-walther/html2pdf#6]
- TYPO3 12.4.17 / Composer mode
- Html2Pdf 12.4.1
- PHP 8.2

Reports Backend Module is broken with this Ext in T3 v12:

**PHP Warning: Undefined array key "contentPostProc-output" in /vendor/carsten-walther/html2pdf/Classes/Report/ExtensionStatus.php line 213**

**Migration notice:**

The hook $GLOBALS['TYPO3_CONF_VARS']['SC_OPTIONS']['tslib/class.tslib_fe.php']['contentPostProc-output'] is not needed as this can be built via a PSR-15 middleware instead, and all content is returned via the RequestHandler of TYPO3 Frontend.

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.4/Deprecation-91012-VariousHooksRelatedToTypoScriptFrontendController.html

**Comment by carsten-walther** [comment]
Fixed in version 12.4.2
